export default {
  START_PAGE_LOADING: "START_PAGE_LOADING",
  STOP_PAGE_LOADING: "STOP_PAGE_LOADING",
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_SUCCESS: "SET_SUCCESS",
  CLEAR_ERROR: "CLEAR_ERROR",
};
