export const actions = {
  SETUP_SESSION: "SETUP_SESSION",
  SET_LOADING: "SET_LOADING",
  STOP_LOADING: "STOP_LOADING",
  JOIN_SESSION: "JOIN_SESSION",
  CLOSE_SESSION: "CLOSE_SESSION",

  SET_HELPING_QUESTION: "SET_HELPING_QUESTION",
  SET_ERROR: "SET_ERROR",
  SET_SUCCESS: "SET_SUCCESS",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};
