export const actions = {
  SET_SESSION: "SET_SESSION",
  SET_LOADING: "SET_LOADING",
  STOP_LOADING: "STOP_LOADING",
  SET_HELPING_QUESTION: "SET_HELPING_QUESTION",
  SET_ERROR: "SET_ERROR",
  SET_SUCCESS: "SET_SUCCESS",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
};
