export default {
  SET_BYPASS_SESSION: "SET_BYPASS_SESSION",
  SET_COURSE: "SET_COURSE",
  SET_SESSION: "SET_SESSION",
  SET_DISCUSSIONS: "SET_DISCUSSIONS",
  SET_ACTIVE_DISCUSSION: "SET_ACTIVE_DISCUSSION",
  SET_QUESTIONS: "SET_QUESTIONS",
  SET_ACTIVE_QUESTION: "SET_ACTIVE_QUESTION",
  SET_STATS: "SET_STATS",
  SET_SORTED_COURSES: "SET_SORTED_COURSES",
};
