export default {
  SET_COURSE: "courses/SET_COURSE",
  SET_SESSION: "courses/SET_SESSION",
  SET_DISCUSSIONS: "courses/SET_DISCUSSIONS",
  SET_ACTIVE_DISCUSSION: "courses/SET_ACTIVE_DISCUSSION",
  SET_QUESTIONS: "courses/SET_QUESTIONS",
  SET_ACTIVE_QUESTION: "courses/SET_ACTIVE_QUESTION",
  SET_STATS: "courses/SET_STATS",
  SET_SORTED_COURSES: "courses/SET_SORTED_COURSES",
};
