const SET_BYPASS_SESSION = "SET_BYPASS_SESSION";
const SET_COURSE = "SET_COURSE";
const SET_SESSION = "SET_SESSION";
const SET_DISCUSSIONS = "SET_DISCUSSIONS";
const SET_ACTIVE_DISCUSSION = "SET_ACTIVE_DISCUSSION";
const SET_QUESTIONS = "SET_QUESTIONS";
const SET_ACTIVE_QUESTION = "SET_ACTIVE_QUESTION";
const SET_STATS = "SET_STATS";

export default {
  SET_BYPASS_SESSION,
  SET_COURSE,
  SET_SESSION,
  SET_DISCUSSIONS,
  SET_ACTIVE_DISCUSSION,
  SET_QUESTIONS,
  SET_ACTIVE_QUESTION,
  SET_STATS,
};
