export const actions = {
  SET_SESSION: "SET_SESSION",
  SET_LOADING: "SET_LOADING",
  SET_QUESTION: "SET_QUESTION",
  EDIT_SUBMISSION: "EDIT_SUBMISSION",
  JOIN_WOTO_ROOM: "JOIN_WOTO_ROOM",
  SET_DISCUSSIONS: "SET_DISCUSSIONS",
  ARCHIVE_DISCUSSION: "ARCHIVE_DISCUSSION",
  EDIT_DISCUSSION: "EDIT_DISCUSSION",
  POST_DISCUSSION: " POST_DISCUSSION",
  LEAVE_DISCUSSION: "LEAVE_DISCUSSION",
  JOIN_DISCUSSION: "JOIN_DISCUSSION",
};
