export const actions = {
  SET_SESSION: "SET_SESSION",
  SET_LOADING: "SET_LOADING",
  SET_QUESTION: "SET_QUESTION",
  SET_STATS: "SET_STATS",
  EDIT_SUBMISSION: "EDIT_SUBMISSION",
  JOIN_WOTO_ROOM: "JOIN_WOTO_ROOM",
  SET_DISCUSSIONS: "SET_DISCUSSIONS",
  SET_DISCUSSION: "SET_DISCUSSION",
  ARCHIVE_DISCUSSION: "ARCHIVE_DISCUSSION",
  LEAVE_DISCUSSION: "LEAVE_DISCUSSION",
  JOIN_DISCUSSION: "JOIN_DISCUSSION",
};
